### ISSUE TITLE
YAML Runner - Allow Client Secret to be passed inline with archivist_runner

### ISSUE THREAD

**Issue by leflambeur** [jitsuin-inc/archivist-python#127]
**Is your feature request related to a problem? Please describe.**
When using the YAML Runner I have to create an extra file to store my client secret only

My client ID has to be passed on the CLI

This is frustrating and non-intuitive when reading the documentation as it is not clear the difference

**Describe the solution you'd like**
I would like to be able to pass my client secret inline on the CLI and not need to put it in a file

I normally use a secret store to populate both variables so have suitable secret security/mgmt in place and would prefer it if the two similar variables consistently followed the same convention 

e.g.

```shell
   archivist_runner \
         -u https://app.rkvst.io \
         --client-id <your-client-id> \
         --client-secret <your-client-secret> \
         functests/test_resources/richness_story.yaml
```

**Describe alternatives you've considered**
If I want to read in the secret from a file later on I can add that to my own code/scripts myself easily enough however I like

Having the secret read in on the cli is more difficult to add manually without writing my own runner code or wrapper so would prefer it to be the native behaviour

**Comment by eccles** [comment]
should be easy - will reuire major version change though

**Comment by leflambeur** [comment]
Understood, looking forward to the next major release then 😁
