### ISSUE TITLE
YAML Runner: Add list locations functionality/examples

### ISSUE THREAD

**Issue by leflambeur** [jitsuin-inc/archivist-python#130]
**Is your feature request related to a problem? Please describe.**
It is possible to create a location and count which attributes are shared between locations but there are no examples that suggest you can get a list of locations you wish to use

**Describe the solution you'd like**
I would like to be able to list all the locations and get data about a specific location in my tenancy to use it in the yaml runner

**Additional context**
We document how to get the location identity with the UI but have no equivalent for the yAML runner - we can however document creating a location and adding it to an asset at creation

**Comment by eccles** [comment]
Thie yaml runner action will be identical to LOCATIONS_COUNT except it will be called LOCATIONS_LIST
