### ISSUE TITLE
Support context managers for Archivist to clean up resources. 

### ISSUE THREAD

**Issue by Serhiy1** [jitsuin-inc/archivist-python#197]
**Is your feature request related to a problem? Please describe.**
Python has context managers for cleaning up resources when a user is done with them.  We should also support this pattern by adding `__enter__()` and `__exit__()` methods. 

Which should make the following possible:
```python
from archivst.archivist import Archivist

with Archivist(URL, auth) as A
     A.assets.list()
     ...
````

**Comment by eccles** [comment]
This was done seprately and this issue forgotten about - closing manually
