### ISSUE TITLE
Sphinx

### ISSUE THREAD

**Issue by MichelHollands** [jitsuin-inc/archivist-python#20]
This looks like fantastic Python code, I've never seen better! 

Would it be possible to show the documentation in the Sphinx format? This would be even more awesome! I can't recommend it more!

**Comment by MichelHollands** [comment]
Please forward this @eccles

**Comment by leflambeur** [comment]
Hey @MichelHollands , thanks for the compliment 😄 

We have API documentation for the platform in Sphinx that can be found here:

https://jitsuin-archivist.readthedocs.io/en/latest/index.html

And the source can be found here:

https://github.com/jitsuin-inc/archivist-docs

We are also working on many improvements to these at the moment including instructions for the SDK so watch this space and any suggestions welcome!

Let me know if this answers your issue or if we can help with anything more specific 🙂

**Comment by eccles** [comment]
fixed
