### ISSUE TITLE
Add "Properties" as an argument to asset creation to bring consistency across the SDK

### ISSUE THREAD

**Issue by Serhiy1** [jitsuin-inc/archivist-python#44]
**Is your feature request related to a problem? Please describe.**
properties are top-level, attributes are second-level - attributes nest under properties. Nearly every endpoint in the SDK apart from asset creation allows properties to be an argument. 

**Describe the solution you'd like**
Add Properties as an argument to asset creation to bring consistency across the SDK

**Comment by JAG-UK** [comment]
Completely agree with this - also will bring us into line with the UI and solve the issue of the confusing vestigial behaviours parameter
