### ISSUE TITLE
RKVST branding and analytics

### ISSUE THREAD

**Issue by eccles** [jitsuin-inc/archivist-python#60]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The generated docs correspond to RKVST branding and colour svheme, fonts etc. Hubspot CRM and Google analytics interfaces added.

**Comment by creator-of-data-assurance-hub** [comment]
The documentation page should have a similar look to the main RKVST.com site. 
Hubspot integration will enable direct communication if needed. 
Google Analytics will help us improve page linking and flow. 

global-palette1: #00aeef;
    --global-palette2: #ffaf09;
    --global-palette3: #001422;
    --global-palette4: #2D3748;
    --global-palette5: #4A5568;
    --global-palette6: #718096;
    --global-palette7: #EDF2F7;
    --global-palette8: #F7FAFC;
    --global-palette9: #FFFFFF;
    --global-palette-highlight: var(--global-palette1);
    --global-palette-highlight-alt: var(--global-palette2);
    --global-palette-highlight-alt2: var(--global-palette9);
    --global-palette-btn-bg: var(--global-palette1);
    --global-palette-btn-bg-hover: var(--global-palette2);
    --global-palette-btn: var(--global-palette9);
    --global-palette-btn-hover: var(--global-palette9);
    --global-body-font-family: 'Open Sans', var(--global-fallback-font);
    --global-heading-font-family: Montserrat, var(--global-fallback-font);
    --global-primary-nav-font-family: Montserrat, var(--global-fallback-font);
    --global-fallback-font: sans-serif;
    --global-content-width: 1290px;

Typeface for headings is Monserrat
Typeface for body text is Open-Sans

**Comment by leflambeur** [comment]
Closing, branding is up to scratch
