### ISSUE TITLE
Adding App Registration and Token Support to the SDK

### ISSUE THREAD

**Issue by leflambeur** [jitsuin-inc/archivist-python#65]
**Is your feature request related to a problem? Please describe.**

I would like a streamlined authentication and access path for RKVST

**Describe the solution you'd like**

Now App Registrations are in production I would like to  manage both my App Registrations with the SDK  and also generate tokens now auth is handled in-house

**Other solutions you've considered**

Using the requests library to manually call the `iam/v1/appidp/token` as auxiliary code

**Comment by eccles** [comment]
This raise interesting possibilities.

      - automatically refresh token when about to expire
      - shorter default TTL for tokens

Discussion:

     - each response to appidp/token is stored in the Archivist instance
     - every call to an endpoint checks the expiry of the token and calls appidp/token to get new one if expired

**Comment by eccles** [comment]
Fixed in latest PR:
