### ISSUE TITLE
Use MyPy in pipeline

### ISSUE THREAD

**Issue by eccles** [jitsuin-inc/archivist-python#79]
**Is your feature request related to a problem? Please describe.**
Type hinting is extensively used but there is no method of automatically checking for errors in the type hinting except by inspection using something like pylance on vscode.

**Describe the solution you'd like**
The utility mypy evidently will do the necessary checks on type hints in the code.

**Additional context**
This is a good project for someone outside of Jitsuin perhaps

**Comment by eccles** [comment]
This is blocked by python 3.6 - an initial trial showed these errors: (note the 'incompatible with 3.6)

rchivist/dictmerge.py:7: error: Skipping analyzing "flatten_dict": module is installed, but missing library stubs or py.typed marker
archivist/timestamp.py:8: error: Skipping analyzing "iso8601": module is installed, but missing library stubs or py.typed marker
archivist/timestamp.py:9: error: Skipping analyzing "rfc3339": module is installed, but missing library stubs or py.typed marker
archivist/sbommetadata.py:8: error: Library stubs not installed for "dataclasses" (or incompatible with Python 3.6)
archivist/compliance_policy_requests.py:7: error: Library stubs not installed for "dataclasses" (or **incompatible with Python 3.6)**
archivist/compliance_policy_requests.py:7: note: Hint: "python3 -m pip install types-dataclasses"
archivist/withdrawer.py:8: error: Skipping analyzing "backoff": module is installed, but missing library stubs or py.typed marker
archivist/uploader.py:6: error: Skipping analyzing "backoff": module is installed, but missing library stubs or py.typed marker
archivist/subjects.py:187: error: Incompatible types in assignment (expression has type "List[str]", target has type "str")
archivist/subjects.py:190: error: Incompatible types in assignment (expression has type "List[str]", target has type "str")
archivist/sboms.py:32: error: Library stubs not installed for "requests.models" (or incompatible with Python 3.6)
archivist/publisher.py:8: error: Skipping analyzing "backoff": module is installed, but missing library stubs or py.typed marker
archivist/confirmer.py:11: error: Skipping analyzing "backoff": module is installed, but missing library stubs or py.typed marker
archivist/attachments.py:30: error: Library stubs not installed for "requests.models" (or incompatible with Python 3.6)
archivist/assets.py:62: error: Variable "archivist.type_aliases.NoneOnError" is not valid as a type
archivist/assets.py:62: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
archivist/assets.py:89: error: Variable "archivist.type_aliases.NoneOnError" is not valid as a type
archivist/assets.py:89: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
archivist/applications.py:180: error: Incompatible types in assignment (expression has type "Dict[Any, Any]", target has type "str")
archivist/archivist.py:42: error: Library stubs not installed for "requests" (or incompatible with Python 3.6)
archivist/archivist.py:42: note: Hint: "python3 -m pip install types-requests"
archivist/archivist.py:42: note: (or run "mypy --install-types" to install all missing stub packages)
archivist/archivist.py:42: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
archivist/archivist.py:43: error: Library stubs not installed for "requests.models" (or incompatible with Python 3.6)
archivist/archivist.py:44: error: Skipping analyzing "requests_toolbelt.multipart.encoder": module is installed, but missing library stubs or py.typed marker
archivist/archivist.py:130: error: Incompatible types in assignment (expression has type "None", variable has type "str")
archivist/archivist.py:131: error: Incompatible types in assignment (expression has type "None", variable has type "str")
archivist/archivist.py:136: error: Need type annotation for "_response_ring_buffer"
archivist/archivist.py:341: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "Optional[Dict[Any, Any]]")

**Comment by eccles** [comment]
Suppressing stubs and untyped imports shows the following puzzles:

archivist/subjects.py:187: error: Incompatible types in assignment (expression has type "List[str]", target has type "str")

This is a simple dict assignment 

           query["wallet_pub_key"] = wallet_pub_keys

there is no type hint for this so what gives?

**Comment by eccles** [comment]
Blocked by https://github.com/jitsuin-inc/archivist-python/issues/88

**Comment by Serhiy1** [comment]
completed in #175
