### ISSUE TITLE
SBOM confirmation should poll until the SBOM is searchable 

### ISSUE THREAD

**Issue by Serhiy1** [jitsuin-inc/archivist-python#91]
**Is your feature request related to a problem? Please describe.**

SBOM upload confirmation does not check whether an SBOM is searchable.  This can lead to intermittent failures as it can take time for the search service to process the SBOM, in which, during that time no changes to the SBOM status can be made. 

**Describe the solution you'd like**
`wait_for_uploading()` should poll until the SBOM is searchable

**Comment by eccles** [comment]
Could not find a way of detecting when an SBOM becomes searchable.
We would have to add the uuid as a search term which seems overkill.

The delay is less than 1 second so solution is to add a caveat in the documentation....

**Comment by eccles** [comment]
Requires backend change which is unlikly to happen.
